[package]
name = "fm-index"
version = "3.0.1"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fm_index"
crate-type = ["cdylib"]

[dependencies]
bytemuck = "1.25.2"
memmap2 = "0.9.11"
num-integer = "0.1.46"
num-traits = "0.2.19"
postcard = { version = "1.1.3", features = ["alloc"] }
pyo3 = { version = "0.29.2", features = ["abi3-py39", "abi3t-py315", "derive" ] }
rayon = "1.12.0"
serde = { version = "1.0.229", features = ["derive"] }
tempfile = "3.27.0"
