from typing import Generator, Iterable, Self

class FMIndex:
    def __init__(self, data: str, on_disk: bool = False) -> None: ...
    def __len__(self) -> int: ...
    def __contains__(self, pattern: str) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __copy__(self) -> Self: ...
    def __deepcopy__(self, memo) -> Self: ...
    def __reduce__(self) -> tuple[type[Self], tuple[str], bytes]: ...
    def __getstate__(self) -> bytes: ...
    def __setstate__(self, state: bytes) -> None: ...
    def item(self) -> str: ...
    def contains(self, pattern: str) -> bool: ...
    def count(self, pattern: str) -> int: ...
    def locate(self, pattern: str) -> list[int]: ...
    def iter_locate(self, pattern: str) -> Generator[int]: ...
    def startswith(self, prefix: str) -> bool: ...
    def endswith(self, suffix: str) -> bool: ...

class MultiFMIndex:
    def __init__(self, data: Iterable[str], on_disk: bool = False) -> None: ...
    def __len__(self) -> int: ...
    def __contains__(self, pattern: str) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __copy__(self) -> Self: ...
    def __deepcopy__(self, memo) -> Self: ...
    def __reduce__(self) -> tuple[type[Self], tuple[list[str]], bytes]: ...
    def __getstate__(self) -> bytes: ...
    def __setstate__(self, state: bytes) -> None: ...
    def item(self) -> list[str]: ...
    def contains(self, pattern: str) -> bool: ...
    def count_all(self, pattern: str) -> int: ...
    def count(self, pattern: str, doc_id: int | None = None) -> dict[int, int] | int: ...
    def topk(self, pattern: str, k: int) -> list[tuple[int, int]]: ...
    def locate(
        self, pattern: str, doc_id: int | None = None
    ) -> dict[int, list[int]] | list[int]: ...
    def iter_locate(
        self, pattern: str, doc_id: int | None = None
    ) -> Generator[int] | Generator[tuple[int, int]]: ...
    def startswith(self, prefix: str) -> list[int]: ...
    def endswith(self, suffix: str) -> list[int]: ...
